CREATE SEQUENCE SEQ_GAMES
    START WITH 1
    INCREMENT BY 1 NOCACHE
  NOCYCLE;

CREATE TABLE TB_GAMES
(
    GAME_ID      INTEGER DEFAULT SEQ_GAMES.NEXTVAL NOT NULL,
    TITLE        VARCHAR2(100) NOT NULL,
    VALUE        DECIMAL(10, 2)                    NOT NULL,
    RELEASE_DATE DATE                              NOT NULL
);

CREATE SEQUENCE SEQ_USERS
    START WITH 1
    INCREMENT BY 1 NOCACHE
  NOCYCLE;

CREATE TABLE TB_USERS
(
    USER_ID  INTEGER DEFAULT SEQ_USERS.NEXTVAL NOT NULL,
    EMAIL    VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    "ROLE"   VARCHAR2(100) DEFAULT USER NULL,
    CONSTRAINT TB_USERS_PK PRIMARY KEY (USER_ID),
    CONSTRAINT TB_USERS_UNIQUE UNIQUE (EMAIL)
);